
class Database{
    String name;
    String No.Handphone;
    
    public static void main (String[] args){
    System.out.println("1. Menu");
    System.out.println("2. Pilih Menu");
    System.out.println("3. Keluar");

    try (Scanner nama = Scanner(System.in);
    System.out.println("Nama :")
    String entry = nama.next();

    try(Scanner no = Scanner(System.in));
    System.out.println("No. Hansphone :")
    Int entry = nama.nextInt();


}